{% set name = "dtreeviz-extended" %}
{% set version = "1.3.6" %}

#
# This should be part of the dtreeviz feedstock as a subpackage,
# but it wasn't working for me (conda-forge has it working).
# 


package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - dtreeviz =={{ version }}
    - pyspark
    - py-xgboost
    - lightgbm

about:
  home: https://github.com/parrt/dtreeviz
  summary: A python library for decision tree visualization and model interpretation
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - raybellwaves
    - pplonski
